name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Install Selenium
        run: |
          pip install selenium webdriver-manager

      - name: Run Keep Alive Script
        run: python keep_alive.py
